# docker-compose.yml
version: "3.9"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:{%40}@db:5432/gauravkharel
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=gauravkharel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD={}
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
