# docker-compose.yml
version: "3.9"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user_name:Database101@@db:5432/gauravkharel
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=gauravkharel
      - POSTGRES_USER=user_name
      - POSTGRES_PASSWORD=Database101@
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
